### ISSUE TITLE
Core review #1

### ISSUE THREAD

**Issue by nidalaa** [SavaVuckovic/Mastermind-Game#2]
😠 
```
ruby index.rb
/Users/nidala/Data/mentoring/microverse/team1/Mastermind-Game/src/ai.rb:2:in `require_relative': /Users/nidala/Data/mentoring/microverse/team1/Mastermind-Game/src/ai_brain.rb:42: syntax error, unexpected =>, expecting keyword_end (SyntaxError)
...length = @@keys_tried.length => 4 ? 0 : 4 - @@keys_tried.len...
...                               ^
	from /Users/nidala/Data/mentoring/microverse/team1/Mastermind-Game/src/ai.rb:2:in `<top (required)>'
	from /Users/nidala/Data/mentoring/microverse/team1/Mastermind-Game/src/game.rb:3:in `require_relative'
	from /Users/nidala/Data/mentoring/microverse/team1/Mastermind-Game/src/game.rb:3:in `<top (required)>'
	from index.rb:1:in `require_relative'
```

😠 

```
/Users/nidala/Data/mentoring/microverse/team1/Mastermind-Game/src/game.rb:108:in `play_round': undefined method `set_last_state' for #<Player:0x007fa20c090280> (NoMethodError)
	from /Users/nidala/Data/mentoring/microverse/team1/Mastermind-Game/src/game.rb:68:in `start_as_guesser'
	from /Users/nidala/Data/mentoring/microverse/team1/Mastermind-Game/src/game.rb:27:in `start_game_loop'
	from /Users/nidala/Data/mentoring/microverse/team1/Mastermind-Game/src/game.rb:16:in `show_home_screen'
	from index.rb:7:in `<main>'```

Committed not working code to master branch? 🙈 What about all thedisappointedd players? 
Let's create a new branch, run your game and fix all crucial 🐛 (might be more than I spotted).

**Comment by talihomz** [comment]
These are now resolved @nidalaa :-)
